# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: coogie/oscailte
title: CoMakingSpace - Heidelberg's Community Makerspace|Let's MAKE a difference together!
email: info@comakingspace.org
description: >- # this means to ignore newlines until "baseurl:"
  CoMakingSpace - Community Workshop in Heidelberg.
  The CoMakingSpace is an open workshop in Heidelberg
  that is built on a combination of Makerspace and Co-Working concepts.
  It is also similar to a FabLab or Hackerspace in many ways - in short: your space for all things "DIY"!
baseurl: "" # the subpath of your site, e.g. /blog
url: "comakingspace.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: comakingspace
github_username: comakingspace

# Build settings
markdown: kramdown

social_links:
    twitter: comakingspace
    github:  comakingspace
    facebook: comakingspace
    instagram: comakingspace