# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
plugins:
  - jekyll-redirect-from

title:
  de: CoMakingSpace - Offene Werkstatt und Makerspace in Heidelberg|Let's MAKE a difference together
  en: CoMakingSpace - Heidelberg's Community Makerspace|Let's MAKE a difference together!
email: info@comakingspace.org
postal_code: 69123
street_address: Siemensstraße 40
country: DE
latitude: 49.4083074
longitude: 8.6465549

description:
  en: >- # this means to ignore newlines until "baseurl:"
    CoMakingSpace - Community Workshop in Heidelberg.
    The CoMakingSpace is an open workshop / makerspace for Makers from all backgrounds. We aim to provide everyone with the tools, space and skills to make whatever they come up with.
    It is also similar to a FabLab or Hackerspace in many ways - in short: your space for all things "DIY"!
  de: >-
    CoMakingSpace - Gemeinschaftswerkstatt in Heidelberg.
    Der CoMakingSpace ist eine offene Werkstatt in Heidelberg, deren Fokus neben dem Makerspace als Ort vor allem auf der Community zum Austausch mit Gleichgesinnten liegt.
    Auch mit einem FabLab oder Hackerspace gibt es viele Parallelen - kurz: dein Raum zum Selbermachen!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.comakingspace.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/CoMakingSpaceLogo.png"
twitter:
  username: comakingspace
  card: summary
github_username: comakingspace
social:
  name: CoMakingSpace
  links:
    - https://twitter.com/comakingspace
    - https://www.facebook.com/comakingspace
    - https://www.linkedin.com/company/comakingspace
    - https://github.com/comakingspace
    - https://www.instagram.com/comakingspace

# Build settings
markdown: kramdown
kramdown:
  auto_id_prefix: "autoid"

social_links:
    twitter: comakingspace
    github:  comakingspace
    facebook: comakingspace
    instagram: comakingspace

timezone: Europe/Berlin

# The defaults are needed in order to not break the header navigation!
defaults:
  -
    scope:
      path: ""
    values:
      ref: "default_ref"
      lang: "de"
